name: Basic Checkout Lab

on:
  push:
    brances:
      - main
jobs:
  basic-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: List Files
        run: ls -la
      
      - name: Show system Info
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Operating system : $(uname -a)"
          echo "Current directory: $(pwd)"
        

      - name: Check Version
        run: |
          echo "Node version: $(node --version)"
          echo "Python version: $(python --version)"
          echo "Git version: $(git --version)"
      - name: Show date and disk Info
        run: |
          echo "Current dtae: $(date)"
          df -h
          free -m
      - name: Custom message
        env: 
          MY_NAME: "RAkib"
        run: echo "Hello $MY_NAME, workflow is running"